trigger:
- master




jobs:
#==============================================================================
# Windows
#==============================================================================
- job: Windows
  
  variables:
  - name: NAMELINT_LLVM_LIB
    value: $(System.DefaultWorkingDirectory)/llvm_8_0_0_msvc2017_rel_32bit
  - name: BUILD_TYPE
    value: Release

  pool:
    vmImage: 'vs2017-win2016'

  steps:
  - script: echo hello from Windows
  - script: 'dir /s'
  - checkout: self
    submodules: true
  
  - task: UniversalPackages@0
    inputs:
      command: 'download'
      downloadDirectory: '$(System.DefaultWorkingDirectory)'
      feedsToUse: 'internal'
      vstsFeed: '78202891-aba0-41ab-952b-2152c4a57470/5d6a84a9-b3ee-4af2-88a9-0e7ceb36156d'
      vstsFeedPackage: '0a8bf302-6f44-4fd6-ab0f-cec0e21d1c99'
      vstsPackageVersion: '0.0.1'
      verbosity: 'Trace'
  - script: 'dir /s'

  - task: CMake@1  
    inputs:
      workingDirectory: 'Build/Win32'
      cmakeArgs: -DCMAKE_BUILD_TYPE=Release ../..

  - task: MSBuild@1
    inputs:
      solution: 'Build/Win32/cppnamelint.sln'
      msbuildVersion: '15.0'
      configuration: 'Release'
      msbuildArchitecture: 'x86' #x86, x64      

  - script: 'dir /s'


  #- script: 'cppazurepipeline.exe'
  #  displayName: 'Execute generated binary file'
  #  workingDirectory: build/Debug


#==============================================================================
# Linux
#==============================================================================
- job: Linux
  
  variables:
  - name: NAMELINT_LLVM_LIB
    value: $(System.DefaultWorkingDirectory)/llvm_8_0_0_ubuntu_18_04_gcc8_rel_64bit
  - name: BUILD_TYPE
    value: Release
  - name: CC
    value: gcc-8
  - name: CXX
    value: g++-8

  pool:
    vmImage: 'ubuntu-18.04'

  steps:
  - script: echo hello from Linux
  - script: 'ls -la'
  - checkout: self
    submodules: true
  
  - task: UniversalPackages@0
    inputs:
      command: 'download'
      downloadDirectory: '$(System.DefaultWorkingDirectory)'
      feedsToUse: 'internal'
      vstsFeed: '78202891-aba0-41ab-952b-2152c4a57470/b5685b00-e1cc-4c03-8f3a-3d3970ac92ee'
      vstsFeedPackage: '2e412881-83ba-43fd-ac45-a050fbbbab59'
      vstsPackageVersion: '0.0.1'
      verbosity: 'Trace'
  - script: 'ls -la'
  - script: 'gcc   --version'
  - script: 'gcc-7 --version'
  - script: 'gcc-8 --version'

  - task: CMake@1  
    inputs:
      workingDirectory: 'build/linux'
      cmakeArgs: -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=gcc-8 -DCMAKE_CXX_COMPILER=g++-8 ../..

  - script: make
    workingDirectory: 'build/linux'

  - script: 'ls -la'

  #- script: 'cppazurepipeline.exe'
  #  displayName: 'Execute generated binary file'
  #  workingDirectory: build/Debug
