trigger:
- master




jobs:
#==============================================================================
# Windows
#==============================================================================
- job: Windows
  
  variables:
  - name: NAMELINT_LLVM_LIB
    value: $(System.DefaultWorkingDirectory)/llvm_8_0_0_msvc2017_rel_32bit

  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: echo hello from Windows
  - script: 'dir /s'
  - checkout: self
    submodules: true
  
  - task: UniversalPackages@0
    inputs:
      command: 'download'
      downloadDirectory: '$(System.DefaultWorkingDirectory)'
      feedsToUse: 'internal'
      vstsFeed: '78202891-aba0-41ab-952b-2152c4a57470/5d6a84a9-b3ee-4af2-88a9-0e7ceb36156d'
      vstsFeedPackage: '0a8bf302-6f44-4fd6-ab0f-cec0e21d1c99'
      vstsPackageVersion: '0.0.1'
      verbosity: 'Trace'
  - script: 'dir /s'

  - task: CMake@1  
    inputs:
      workingDirectory: 'Build/Win32'
      cmakeArgs: -DCMAKE_BUILD_TYPE=Release ../..

  - task: MSBuild@1
    inputs:    
      solution: 'Build/Win32/cppnamelint.sln'        
      msbuildVersion: '15.0' 
      msbuildArchitecture: 'x86' #x86, x64      


  #- script: 'cppazurepipeline.exe'
  #  displayName: 'Execute generated binary file'
  #  workingDirectory: build/Debug
