trigger:
- master


jobs:
#==============================================================================
# Windows
#==============================================================================
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: echo hello from Windows
  - script: 'dir /s'
  - checkout: self
    submodules: true
    
  - task: CMake@1
    inputs:
      workingDirectory: 'Build/Win32'
      cmakeArgs: ../..
  - task: MSBuild@1
    inputs:    
      solution: 'Build/Win32/cppnamelint.sln'        
      msbuildVersion: '15.0' 
      msbuildArchitecture: 'x86' #x86, x64

  #- script: 'cppazurepipeline.exe'
  #  displayName: 'Execute generated binary file'
  #  workingDirectory: build/Debug
