trigger:
  - master
  - feature*
  - m_douglas*
  - issue*

jobs:
  #==============================================================================
  # Windows
  #==============================================================================
  - job: BuildOnWindows

    variables:
      - name: NAMELINT_LLVM_LIB
        value: $(System.DefaultWorkingDirectory)/llvm_8_0_0_msvc2019_rel_64bit
      - name: BUILD_TYPE
        value: Release

    pool:
      vmImage: "windows-2019"

    steps:
      - script: "set"
        displayName: "Dump Azure environment variables."

      - checkout: self
        displayName: "Checkout git submodules."
        submodules: true

      - task: UniversalPackages@0
        inputs:
          command: 'download'
          downloadDirectory: '$(System.DefaultWorkingDirectory)'
          feedsToUse: 'internal'
          vstsFeed: '78202891-aba0-41ab-952b-2152c4a57470/688423ed-1bc6-41cc-87aa-0938d537e60a'
          vstsFeedPackage: 'e88fcc0d-0d86-47a0-a895-9e77f98c1c0c'
          vstsPackageVersion: '0.0.1'
          verbosity: 'Trace'

      - task: PowerShell@2
        inputs:
          script: tree -f c:\

      - task: PowerShell@2
        inputs:
          filePath: 'script/build-bin-win32.ps1'
          workingDirectory: 'script'

      - task: MSBuild@1
        inputs:
          solution: "build/windows/cppnamelint.sln"
          msbuildVersion: "15.0"
          configuration: "Release"
          msbuildArchitecture: "x86" #x86, x64
          
      - task: PowerShell@2
        inputs:
          filePath: 'script/build-pack-win32.ps1'
          workingDirectory: 'script'

      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: 'script\release\windows'
          includeRootFolder: false
          archiveType: '7z'
          archiveFile: 'cppnamelint-win32.7z'
          replaceExistingArchive: true
          verbose: true

      - task: GitHubRelease@1
        inputs:
          gitHubConnection: 'github.com_dougpuob'
          repositoryName: 'dougpuob/cpp-namelint'
          action: 'edit'
          target: '$(Build.SourceVersion)'
          tag: 'v0.3*'
          assets: 'cppnamelint-win32.7z'
          assetUploadMode: 'replace'
          isDraft: true
          isPreRelease: true
          changeLogCompareToRelease: 'lastFullRelease'
          changeLogType: 'issueBased'

      - task: PowerShell@2
        inputs:
          filePath: 'script/build-test-win32.ps1'
          workingDirectory: 'script/release/windows'

          
  #==============================================================================
  # Linux
  #==============================================================================
  - job: BuildOnLinux

    variables:
      - name: NAMELINT_LLVM_LIB
        value: $(System.DefaultWorkingDirectory)/llvm_8_0_0_ubuntu_18_04_gcc_7_4_rel_64bit
      - name: BUILD_TYPE
        value: Release
      - name: CC
        value: gcc
      - name: CXX
        value: g++

    pool:
      vmImage: "ubuntu-18.04"

    steps:
      - script: "gcc --version"
        displayName: "Show gcc version."

      - script: "export"
        displayName: "Dump Azure environment variables."

      - checkout: self
        displayName: "Checkout git submodules."
        submodules: true

      - task: UniversalPackages@0
        inputs:
          command: "download"
          downloadDirectory: "$(System.DefaultWorkingDirectory)"
          feedsToUse: "internal"
          vstsFeed: "78202891-aba0-41ab-952b-2152c4a57470/1d266e96-42a9-4468-83b0-69b039e87cb3"
          vstsFeedPackage: "e8febc2a-50f8-4b36-832d-87feb38f96f0"
          vstsPackageVersion: "0.0.2"
          verbosity: "Trace"
      - script: "ls -la"

      #- script: "ls -la -R"
      #  displayName: "Dump folder hierarchy"

      - script: "./build-bin-linux.sh"
        displayName: "build-bin-linux.sh"
        workingDirectory: "script"

      - script: make
        workingDirectory: "build/linux"

      #- script: "ls -la -R"
      #  displayName: "Dump folder hierarchy"

      - script: "./build-pack-linux.sh"
        displayName: "build-pack-linux.sh"
        workingDirectory: "script"

      #- script: "ls -la -R"
      #  displayName: "Dump folder hierarchy"

      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: 'script/release/linux'
          includeRootFolder: false
          archiveType: '7z'
          archiveFile: 'cppnamelint-ubuntu-18.04.7z'
          replaceExistingArchive: true
          verbose: true

      - task: GitHubRelease@1
        inputs:
          gitHubConnection: 'github.com_dougpuob'
          repositoryName: 'dougpuob/cpp-namelint'
          action: 'edit'
          target: '$(Build.SourceVersion)'
          tag: 'v0.3*'
          assets: 'cppnamelint-ubuntu-18.04.7z'
          assetUploadMode: 'replace'
          isDraft: true
          isPreRelease: true
          changeLogCompareToRelease: 'lastFullRelease'
          changeLogType: 'issueBased'


      - script: "./build-test-linux.sh"
        displayName: "build-test-linux.sh"
        workingDirectory: "script/release/linux"


  #==============================================================================
  # macOS ("macOS-10.14")
  #==============================================================================
  - job: BuildOnMacOS

    variables:
      - name: NAMELINT_LLVM_LIB
        value: $(System.DefaultWorkingDirectory)/llvm_8_0_0_macos_10_14_5_clang_10_rel_64bit
      - name: BUILD_TYPE
        value: Release
      - name: CC
        value: clang
      - name: CXX
        value: clang++

    pool:
      vmImage: "macOS-10.14"

    steps:
      - script: "clang --version"
        displayName: "Show gcc version."

      - script: "export"
        displayName: "Dump Azure environment variables."

      - checkout: self
        displayName: "Checkout git submodules."
        submodules: true

      - task: UniversalPackages@0
        inputs:
          command: "download"
          downloadDirectory: "$(System.DefaultWorkingDirectory)"
          feedsToUse: "internal"
          vstsFeed: "78202891-aba0-41ab-952b-2152c4a57470/7bc16282-7635-45e1-821a-373ed55c68c5"
          vstsFeedPackage: "1ea8f4a8-0c01-4eb1-8fbf-e514f8768b5e"
          vstsPackageVersion: "0.0.1"
          verbosity: "Trace"

      - task: Bash@3
        inputs:
          filePath: 'script/build-bin-macos.sh'
          workingDirectory: 'script'

      - script: make
        workingDirectory: "build/macos"

      - task: Bash@3
        inputs:
          filePath: 'script/build-pack-linux.sh'
          workingDirectory: 'script'

      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: 'script/release/macos'
          includeRootFolder: false
          archiveType: 'zip'
          archiveFile: 'cppnamelint-macos-10.14.7z'
          replaceExistingArchive: true
          verbose: true
          
      - script: "./build-test-linux.sh"
        displayName: "build-test-linux.sh"
        workingDirectory: "script/release/macos"

      - task: GitHubRelease@1
        inputs:
          gitHubConnection: 'github.com_dougpuob'
          repositoryName: 'dougpuob/cpp-namelint'
          action: 'edit'
          target: '$(Build.SourceVersion)'
          tag: 'v0.3*'
          assets: 'cppnamelint-macos-10.14.7z'
          assetUploadMode: 'replace'
          isDraft: true
          isPreRelease: true
          changeLogCompareToRelease: 'lastFullRelease'
          changeLogType: 'issueBased'
