trigger:
- master




jobs:
#==============================================================================
# Windows
#==============================================================================
- job: Windows
  
  variables:
  - name: NAMELINT_LLVM_LIB
    value: $(System.DefaultWorkingDirectory)/llvm_8_0_0_msvc2017_rel_32bit
  - name: BUILD_TYPE
    value: Release

  pool:
    vmImage: 'vs2017-win2016'

  steps:
  - script: echo hello from Windows
  - script: 'dir /s'
  - checkout: self
    submodules: true
  
  - task: UniversalPackages@0
    inputs:
      command: 'download'
      downloadDirectory: '$(System.DefaultWorkingDirectory)'
      feedsToUse: 'internal'
      vstsFeed: '78202891-aba0-41ab-952b-2152c4a57470/5d6a84a9-b3ee-4af2-88a9-0e7ceb36156d'
      vstsFeedPackage: '0a8bf302-6f44-4fd6-ab0f-cec0e21d1c99'
      vstsPackageVersion: '0.0.1'
      verbosity: 'Trace'
  - script: 'dir /s'

  - task: CMake@1  
    inputs:
      workingDirectory: 'Build/Win32'
      cmakeArgs: -DCMAKE_BUILD_TYPE=Release ../..

  - task: MSBuild@1
    inputs:
      solution: 'Build/Win32/cppnamelint.sln'
      msbuildVersion: '15.0'
      configuration: 'Release'
      msbuildArchitecture: 'x86' #x86, x64      

  - script: 'dir /s'

  - task: badge-creator@1
    inputs:
      nameString: 'build for win'
      versionString: '0.0.23'
      destinationPath: '$(build.artifactstagingdirectory)/badge.svg'

  #- script: 'cppazurepipeline.exe'
  #  displayName: 'Execute generated binary file'
  #  workingDirectory: build/Debug


#==============================================================================
# Linux
#==============================================================================
- job: Linux
  
  variables:
  - name: NAMELINT_LLVM_LIB
    value: $(System.DefaultWorkingDirectory)/llvm_8_0_0_ubuntu_18_04_gcc8_rel_64bit
  - name: BUILD_TYPE
    value: Release

  pool:
    vmImage: 'ubuntu-18.04'

  steps:
  - script: echo hello from Linux
  - script: 'ls -la'
  - checkout: self
    submodules: true
  
  - task: UniversalPackages@0
    inputs:
      command: 'download'
      downloadDirectory: '$(System.DefaultWorkingDirectory)'
      feedsToUse: 'internal'
      vstsFeed: '78202891-aba0-41ab-952b-2152c4a57470/3dc15bc1-c48e-4b46-894b-1121b8510008'
      vstsFeedPackage: 'cf9574f8-9f88-4bae-a44a-1a163e890de3'
      vstsPackageVersion: '0.0.1'
      verbosity: 'Trace'
  - script: 'ls -la'
  
  - task: CMake@1  
    inputs:
      workingDirectory: 'build/linux'
      cmakeArgs: -DCMAKE_BUILD_TYPE=Release ../..

  - script: make
  - script: 'ls -la'

  #- script: 'cppazurepipeline.exe'
  #  displayName: 'Execute generated binary file'
  #  workingDirectory: build/Debug
