trigger:
  - master
  - dev
  - neville1


jobs:
#==============================================================================
# Windows
#==============================================================================
- job: Windows
  
  variables:
  - name: NAMELINT_LLVM_LIB
    value: $(System.DefaultWorkingDirectory)/llvm_8_0_0_msvc2017_rel_32bit
  - name: BUILD_TYPE
    value: Release

  pool:
    vmImage: 'vs2017-win2016'

  steps:
  - script: echo hello from Windows
  - script: 'dir /s'
  - checkout: self
    submodules: true
  
  - task: UniversalPackages@0
    inputs:
      command: 'download'
      downloadDirectory: '$(System.DefaultWorkingDirectory)'
      feedsToUse: 'internal'
      vstsFeed: '78202891-aba0-41ab-952b-2152c4a57470/5d6a84a9-b3ee-4af2-88a9-0e7ceb36156d'
      vstsFeedPackage: '0a8bf302-6f44-4fd6-ab0f-cec0e21d1c99'
      vstsPackageVersion: '0.0.1'
      verbosity: 'Trace'
  - script: 'dir /s'

  - task: CMake@1  
    inputs:
      workingDirectory: 'build/windows'
      cmakeArgs: -DCMAKE_BUILD_TYPE=Release ../..

  - task: MSBuild@1
    inputs:
      solution: 'build/windows/cppnamelint.sln'
      msbuildVersion: '15.0'
      configuration: 'Release'
      msbuildArchitecture: 'x86' #x86, x64      

  - script: 'dir /s'

  - script: 'cppnamelint.exe test -a'
    displayName: 'Execute generated binary file'
    workingDirectory: 'build\windows\output\Release'


#==============================================================================
# Linux
#==============================================================================
- job: Linux
  
  variables:
  - name: NAMELINT_LLVM_LIB
    value: $(System.DefaultWorkingDirectory)/llvm_8_0_0_ubuntu_18_04_gcc_7_4_rel_64bit
  - name: BUILD_TYPE
    value: Release
  - name: CC
    value: gcc
  - name: CXX
    value: g++
  pool:
    vmImage: 'ubuntu-18.04'

  steps:
  - script: echo hello from Linux
  - script: 'ls -la'
  - checkout: self
    submodules: true
  
  - task: UniversalPackages@0
    inputs:
      command: 'download'
      downloadDirectory: '$(System.DefaultWorkingDirectory)'
      feedsToUse: 'internal'
      vstsFeed: '78202891-aba0-41ab-952b-2152c4a57470/1d266e96-42a9-4468-83b0-69b039e87cb3'
      vstsFeedPackage: 'e8febc2a-50f8-4b36-832d-87feb38f96f0'
      vstsPackageVersion: '0.0.2'
      verbosity: 'Trace'
  - script: 'ls -la'
  - script: 'gcc   --version'

  - task: CMake@1  
    inputs:
      workingDirectory: 'build/linux'
      cmakeArgs: -DCMAKE_BUILD_TYPE=Release  ../..

  - script: make
    workingDirectory: 'build/linux'

  - script: 'ls -ls -R'

  - script: './cppnamelint test -a'
    displayName: 'Execute generated binary file'
    workingDirectory: 'build/linux/output'



#==============================================================================
# Linux
#==============================================================================
- job: macOS
  
  variables:
  - name: NAMELINT_LLVM_LIB
    value: $(System.DefaultWorkingDirectory)/llvm_8_0_0_macos_10_14_5_clang_10_rel_64bit
  - name: BUILD_TYPE
    value: Release
  - name: CC
    value: clang
  - name: CXX
    value: clang++
  pool:
    vmImage: 'macOS-10.13'

  steps:
  - script: echo hello from macOS
  - script: 'ls -ls -R'
  - checkout: self
    submodules: true
  
  - task: UniversalPackages@0
    inputs:
      command: 'download'
      downloadDirectory: '$(System.DefaultWorkingDirectory)'
      feedsToUse: 'internal'
      vstsFeed: '78202891-aba0-41ab-952b-2152c4a57470/7bc16282-7635-45e1-821a-373ed55c68c5'
      vstsFeedPackage: '1ea8f4a8-0c01-4eb1-8fbf-e514f8768b5e'
      vstsPackageVersion: '0.0.1'
      verbosity: 'Trace'
  - script: 'ls -ls -R'

  - task: CMake@1  
    inputs:
      workingDirectory: 'build/darwin'
      cmakeArgs: -DCMAKE_BUILD_TYPE=Release  ../..

  - script: make
    workingDirectory: 'build/darwin'

  - script: 'ls -ls -R'

  - script: './cppnamelint test -a'
    displayName: 'Execute generated binary file'
    workingDirectory: 'build/darwin/output'
